apiVersion: v1
kind: Service
metadata:
  name: service-2023mt03575
spec:
  selector:
    app: fastapi-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30075